alias apar="sudo apt autoremove"
alias apdp="sudo apt depends"
alias apdt="sudo apt dotted"
alias apfl="sudo apt-file list"
alias apfs="sudo apt-file search"
alias api="sudo apt install"
alias apr="sudo apt remove"
alias aprd="sudo apt rdepends"
alias aps="sudo apt search --names-only"
alias apsh="sudo apt show"
alias apud="sudo apt update"
alias apug="sudo apt upgrade"

alias aff="apt-file find"
alias afl="apt-file list"
alias afu="sudo apt-file update"
